// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Follow = sequelize.define('follow', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    follwingId: {
      type: DataTypes.INTEGER,
      field: 'FollwingId',
      primaryKey: true,
      allowNull: false,
    },
    follwerId: {
      type: DataTypes.INTEGER,
      field: 'FollwerId',
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'follow',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Follow.associate = (models) => {
    Follow.belongsTo(models.users, {
      foreignKey: {
        name: 'followerIdKey',
        field: 'FollowerId',
      },
      as: 'follower',
    });
    Follow.belongsTo(models.users, {
      foreignKey: {
        name: 'followingIdKey',
        field: 'followingId',
      },
      as: 'following',
    });
    Follow.belongsTo(models.users, {
      foreignKey: {
        name: 'follwingIdKey',
        field: 'FollwingId',
      },
      as: 'follwing',
    });
    Follow.belongsTo(models.users, {
      foreignKey: {
        name: 'followerIdKey',
        field: 'followerId',
      },
      as: 'followerFollowerId',
    });
    Follow.belongsTo(models.users, {
      foreignKey: {
        name: 'followingIdKey',
        field: 'FollowingId',
      },
      as: 'followingFollowingId',
    });
    Follow.belongsTo(models.users, {
      foreignKey: {
        name: 'follwerIdKey',
        field: 'FollwerId',
      },
      as: 'follwer',
    });
  };

  return Follow;
};
