// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Users = sequelize.define('users', {
    email: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    nickname: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'users',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Users.associate = (models) => {
    Users.belongsToMany(models.posts, {
      through: 'like',
      foreignKey: 'UserId',
      otherKey: 'PostId',
      as: 'postsThroughLikes',
    });
    Users.hasMany(models.comments, {
      foreignKey: {
        name: 'userIdKey',
        field: 'UserId',
      },
      as: 'comments',
    });
    Users.hasMany(models.follow, {
      foreignKey: {
        name: 'followerIdKey',
        field: 'FollowerId',
      },
      as: 'followerFollows',
    });
    Users.hasMany(models.follow, {
      foreignKey: {
        name: 'followingIdKey',
        field: 'followingId',
      },
      as: 'followingFollows',
    });
    Users.hasMany(models.follow, {
      foreignKey: {
        name: 'follwingIdKey',
        field: 'FollwingId',
      },
      as: 'follwingFollows',
    });
    Users.hasMany(models.follow, {
      foreignKey: {
        name: 'followerIdKey',
        field: 'followerId',
      },
      as: 'followerFollowsFollowerId',
    });
    Users.hasMany(models.follow, {
      foreignKey: {
        name: 'followingIdKey',
        field: 'FollowingId',
      },
      as: 'followingFollowsFollowingId',
    });
    Users.hasMany(models.follow, {
      foreignKey: {
        name: 'follwerIdKey',
        field: 'FollwerId',
      },
      as: 'follwerFollows',
    });
    Users.hasMany(models.posts, {
      foreignKey: {
        name: 'userIdKey',
        field: 'UserId',
      },
      as: 'posts',
    });
  };

  return Users;
};
